import type {
  Article,
  Brand,
  Category,
  InventoryState,
  Movement,
  ReportFilter,
  StockEntry,
  StockRequest,
} from "@/lib/types";

export const brands: Brand[] = [
  { id: "brand-asuka-spirit", name: "ASUKA SPIRIT" },
  { id: "brand-docteur-asuka", name: "Docteur Asuka" },
];

export const categories: Category[] = [
  {
    id: "cat-laptops",
    brandId: "brand-asuka-spirit",
    name: "Ordinateurs portables",
  },
  {
    id: "cat-smartwatches",
    brandId: "brand-asuka-spirit",
    name: "Montres connectees",
  },
  {
    id: "cat-smart-glasses",
    brandId: "brand-asuka-spirit",
    name: "Lunettes connectees",
  },
  {
    id: "cat-repair-screens",
    brandId: "brand-docteur-asuka",
    name: "Ecrans de reparation",
  },
  {
    id: "cat-repair-tools",
    brandId: "brand-docteur-asuka",
    name: "Outils de reparation",
  },
  {
    id: "cat-electronic-parts",
    brandId: "brand-docteur-asuka",
    name: "Pieces electroniques",
  },
];

export const articles: Article[] = [
  {
    id: "art-air14",
    name: "ASUKA SPIRIT Air 14",
    brandId: "brand-asuka-spirit",
    categoryId: "cat-laptops",
    reference: "ASS-AIR14-I5",
    availableQty: 18,
    alertThreshold: 6,
    location: "Showroom A1",
    condition: "new",
    unit: "piece",
  },
  {
    id: "art-watch-s3",
    name: "ASUKA SPIRIT Watch S3",
    brandId: "brand-asuka-spirit",
    categoryId: "cat-smartwatches",
    reference: "ASS-WS3-AMOLED",
    availableQty: 9,
    alertThreshold: 10,
    location: "Vitrine B2",
    condition: "new",
    unit: "piece",
  },
  {
    id: "art-glass-xr",
    name: "ASUKA SPIRIT Vision XR",
    brandId: "brand-asuka-spirit",
    categoryId: "cat-smart-glasses",
    reference: "ASS-VXR-128",
    availableQty: 5,
    alertThreshold: 4,
    location: "Coffre produit C1",
    condition: "new",
    unit: "piece",
  },
  {
    id: "art-screen-ip13",
    name: "Ecran iPhone 13 OLED",
    brandId: "brand-docteur-asuka",
    categoryId: "cat-repair-screens",
    reference: "DRA-SCR-IP13-OLED",
    availableQty: 4,
    alertThreshold: 6,
    location: "Tiroir SAV E4",
    condition: "good",
    unit: "piece",
  },
  {
    id: "art-screen-a54",
    name: "Ecran Samsung Galaxy A54",
    brandId: "brand-docteur-asuka",
    categoryId: "cat-repair-screens",
    reference: "DRA-SCR-A54-AMOLED",
    availableQty: 7,
    alertThreshold: 8,
    location: "Tiroir SAV E5",
    condition: "good",
    unit: "piece",
  },
  {
    id: "art-screwdriver-kit",
    name: "Kit tournevis precision 80 en 1",
    brandId: "brand-docteur-asuka",
    categoryId: "cat-repair-tools",
    reference: "DRA-TOOL-80IN1",
    availableQty: 11,
    alertThreshold: 5,
    location: "Atelier SAV A2",
    condition: "used",
    unit: "kit",
  },
  {
    id: "art-connector-c",
    name: "Connecteur USB-C universel",
    brandId: "brand-docteur-asuka",
    categoryId: "cat-electronic-parts",
    reference: "DRA-CON-USB-C",
    availableQty: 132,
    alertThreshold: 40,
    location: "Bac micro-piece P3",
    condition: "new",
    unit: "piece",
  },
  {
    id: "art-battery-watch",
    name: "Batterie ASUKA SPIRIT Watch S3",
    brandId: "brand-docteur-asuka",
    categoryId: "cat-electronic-parts",
    reference: "DRA-BAT-WS3",
    availableQty: 22,
    alertThreshold: 12,
    location: "Bac micro-piece P5",
    condition: "new",
    unit: "piece",
  },
];

export const entries: StockEntry[] = [
  {
    id: "ent-1001",
    articleId: "art-watch-s3",
    quantity: 6,
    source: "Usine Shenzhen - lot avril",
    date: "2026-04-14T09:10:00.000Z",
    recordedBy: "Loic K.",
    note: "Reassort vitrine pour ASUKA SPIRIT Watch S3",
  },
  {
    id: "ent-1002",
    articleId: "art-connector-c",
    quantity: 80,
    source: "Fournisseur Shenzhen Repair Parts",
    date: "2026-04-13T15:45:00.000Z",
    recordedBy: "Sandra A.",
    note: "Reassort SAV connecteurs USB-C",
  },
  {
    id: "ent-1003",
    articleId: "art-screen-a54",
    quantity: 5,
    source: "Grossiste mobile Abidjan",
    date: "2026-04-12T10:20:00.000Z",
    recordedBy: "Loic K.",
    note: "Livraison partielle ecrans Galaxy A54",
  },
];

export const requests: StockRequest[] = [
  {
    id: "req-2001",
    requester: "Brice Houngbe",
    articleId: "art-screen-ip13",
    quantity: 2,
    reason: "Reparation ticket SAV-IP13-582",
    jobReference: "SAV-COT-582",
    status: "pending",
    requestedAt: "2026-04-15T08:20:00.000Z",
  },
  {
    id: "req-2002",
    requester: "Mireille Sossa",
    articleId: "art-watch-s3",
    quantity: 3,
    reason: "Preparation vitrine showroom Porto-Novo",
    jobReference: "SHOW-PN-014",
    status: "pending",
    requestedAt: "2026-04-15T09:05:00.000Z",
  },
  {
    id: "req-2003",
    requester: "Alain Dossou",
    articleId: "art-screwdriver-kit",
    quantity: 1,
    reason: "Diagnostic atelier reparation premium",
    jobReference: "SAV-ATL-311",
    status: "approved",
    requestedAt: "2026-04-14T11:15:00.000Z",
    reviewComment: "Sortie autorisee",
  },
  {
    id: "req-2004",
    requester: "Ruth Kiki",
    articleId: "art-screen-a54",
    quantity: 5,
    reason: "Serie de reparation Galaxy A54 en attente",
    jobReference: "SAV-LOT-A54",
    status: "rejected",
    requestedAt: "2026-04-13T16:30:00.000Z",
    reviewComment: "Quantite trop elevee pour le stock restant",
  },
];

export const movements: Movement[] = [
  {
    id: "mov-3001",
    type: "entry",
    articleId: "art-watch-s3",
    quantity: 6,
    actor: "Loic K.",
    date: "2026-04-14T09:10:00.000Z",
    note: "Reception lot ASUKA SPIRIT Watch S3",
  },
  {
    id: "mov-3002",
    type: "output",
    articleId: "art-screwdriver-kit",
    quantity: 1,
    actor: "Alain Dossou",
    relatedRequestId: "req-2003",
    date: "2026-04-14T12:10:00.000Z",
    note: "Sortie atelier Docteur Asuka",
  },
  {
    id: "mov-3003",
    type: "approval",
    articleId: "art-screwdriver-kit",
    quantity: 1,
    actor: "Responsable terrain",
    relatedRequestId: "req-2003",
    date: "2026-04-14T11:45:00.000Z",
    note: "Validation a distance",
  },
  {
    id: "mov-3004",
    type: "entry",
    articleId: "art-connector-c",
    quantity: 80,
    actor: "Sandra A.",
    date: "2026-04-13T15:45:00.000Z",
    note: "Reception pieces micro-soudure USB-C",
  },
  {
    id: "mov-3005",
    type: "rejection",
    articleId: "art-screen-a54",
    quantity: 5,
    actor: "Responsable terrain",
    relatedRequestId: "req-2004",
    date: "2026-04-13T17:05:00.000Z",
    note: "Demande refusee pour eviter une rupture SAV",
  },
  {
    id: "mov-3006",
    type: "output",
    articleId: "art-air14",
    quantity: 4,
    actor: "Equipe showroom Cotonou",
    date: "2026-04-12T13:20:00.000Z",
    note: "Mise en rayon lancement ASUKA SPIRIT Air 14",
  },
  {
    id: "mov-3007",
    type: "return",
    articleId: "art-glass-xr",
    quantity: 3,
    actor: "Showroom principal",
    date: "2026-04-12T17:40:00.000Z",
    note: "Retour demo apres presentation client",
  },
  {
    id: "mov-3008",
    type: "adjustment",
    articleId: "art-battery-watch",
    quantity: 2,
    actor: "Loic K.",
    date: "2026-04-11T14:05:00.000Z",
    note: "Ajustement apres inventaire des pieces Watch S3",
  },
];

export const defaultReportFilter: ReportFilter = {
  period: "weekly",
  startDate: "2026-04-08",
  endDate: "2026-04-15",
};

export const inventorySeed: InventoryState = {
  brands,
  categories,
  articles,
  entries,
  requests,
  movements,
};

export const technicians = [
  "Brice Houngbe",
  "Mireille Sossa",
  "Alain Dossou",
  "Ruth Kiki",
  "Equipe showroom Cotonou",
];
